name: ErfanGSI-build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Прямая ссылка на прошивку:'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/sagit/20230302/lineage-20.0-20230302-nightly-sagit-signed.zip'
      REPACK_NAME:
        description: 'Имя сжатого файла:'
        required: true
        default: 'Compressed.7z'
      ROM_TYPE:
        description: 'Тип GSI (Generic, Pixel, etc.) '
        required: true
        default: 'Generic'
env:
  TELEGRAM_TO: 1214932938
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  build_tosasitill_GSI:
    runs-on: ubuntu-20.04

    steps:
      - name: 获取源代码
        uses: actions/checkout@main
        with:
          path: ErfanGSIs

      - name: Настройка времени...
        run: |
          echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
          echo "BUILD_sTIME=$(TZ=Asia/Shanghai date -d @$(date +%s) +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV

      - name: Установка зависимостей...
        run: |
          sudo apt install -y git wget git gzip unzip curl axel aria2 zstd rename p7zip-full pigz

      - name: Установка cxdGSI...
        uses: actions/checkout@main
        with:
          repository: tosasitill/erfanSGSI
          path: ErfanGSIs

      - name: Выдача прав 777...
        run: |
          sudo chmod 777 -R $GITHUB_WORKSPACE/ErfanGSIs

      - name: Закрытие запущенных процессов...
        run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh

      - name: Настройка cxdGSI...
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/ErfanGSIs/setup.sh
          sudo bash $GITHUB_WORKSPACE/ErfanGSIs/setup.sh
          sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
          java -version
          pip3 install aligo

      - name: Скачивание прошивки и преобразование в GSI-образ...
        run: |
          cd ${{ github.workspace }}/ErfanGSIs/
          sudo bash ./url2GSI.sh --ab ${{ github.event.inputs.ROM_URL }} ${{ github.event.inputs.ROM_TYPE }}

      - name: Архивация GSI...
        if: ${{ github.event.inputs.ALI }} != '1'
        run: |
          cd $GITHUB_WORKSPACE/ErfanGSIs
          pwd
          7za a -mmt16 -t7z -r tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} output/*
          ls "tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}"
          mkdir upload_ab
          ls upload_ab
          if [ $(ls -l tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} | awk '{print $5}') -gt 2147483647 ]; then tar cvzpf - tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} | split -d -b 1024m - upload_ab/tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}; else mv tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} upload_ab/tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}; fi

      - name: Загрузка на GitHub Releases...
        if: ${{ github.event.inputs.ALI }} != '1'
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{ github.workspace }}/ErfanGSIs/upload_ab/*"
          tag: "${{ github.event.inputs.REPACK_NAME }}_${{ env.BUILD_TIME }}"
          bodyFile: "${{ github.workspace }}/ErfanGSIs/output/build_info.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
